
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Use the same constants as src/lib/supabase.ts
import { supabase } from '@/lib/supabase';

// Export the supabase instance from lib to avoid creating multiple instances
export { supabase };
